kind: Secret
apiVersion: v1
metadata:
  namespace: vplugin-demo
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "vplugin/data/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
