kind: Secret
apiVersion: v1
metadata:
  namespace: vplugin-demo
  name: example-secret
  annotations:
    avp_path: "data/vplugin/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
